# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run UI Tests"
  lane :run_ui_tests do
    sh "killall Simulator || true"  # Terminate any running simulators
    sh "xcrun simctl shutdown all"  # Shutdown every simulator
    sh "xcrun simctl erase all"  # Reset simulators before running tests
    sh "xcrun simctl boot 'iPhone 16 Pro'"  # Start Simulator so fastlane can find it
    scan(
      project: "client.xcodeproj",
      scheme: "clientUITests",
#      destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2",
      devices: ["iPhone 16 Pro"],
      testplan: "clientUITests",
      clean: true,
      derived_data_path: "build/DerivedData",
      output_types: "junit,html",
      output_directory: "./TestReports",
      parallel_testing: false,
      fail_build: true
    )
  sh "killall Simulator || true"  # Ensure all simulators are closed after tests
  end
  
  lane :build_release do
  build_app(
    workspace: "YourApp.xcworkspace",
    scheme: "YourAppScheme",
    clean: true,
    configuration: "Release",
    export_method: "app-store",
    output_directory: "./build",
    output_name: "YourApp.ipa"
  )
  end
end
