name: Builds

on: [ pull_request ]

jobs:

  compile_mac:
    name: Compile for MacOS
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: xcodebuild -project "client.xcodeproj" -scheme "client" -sdk=macosx -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  compile_ios:
    name: Compile for iOS
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: xcodebuild -project "client.xcodeproj" -scheme "client" -sdk=iphonesimulator -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
