name: Tests

on: [ pull_request ]

jobs:

  unit_tests:
    name: Run Unit-Tests
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Unit-Tests
        run: cd client; sh runUnitTests.sh
